/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router
import { createFileRoute } from '@tanstack/react-router';
// Import Routes
import { Route as rootRoute } from './routes/__root';
// Create Virtual Routes
const UsernameLazyImport = createFileRoute('/username')();
const LoginLazyImport = createFileRoute('/login')();
const IndexLazyImport = createFileRoute('/')();
// Create/Update Routes
const UsernameLazyRoute = UsernameLazyImport.update({
    path: '/username',
    getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/username.lazy').then((d) => d.Route));
const LoginLazyRoute = LoginLazyImport.update({
    path: '/login',
    getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/login.lazy').then((d) => d.Route));
const IndexLazyRoute = IndexLazyImport.update({
    path: '/',
    getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/index.lazy').then((d) => d.Route));
// Create and export the route tree
export const routeTree = rootRoute.addChildren({
    IndexLazyRoute,
    LoginLazyRoute,
    UsernameLazyRoute,
});
/* prettier-ignore-end */
/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/username"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/username": {
      "filePath": "username.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
